version: '3' 
services: 
  my_mongo:
    image: mongo
    ports: 
      - 27017:27017
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  mongo-express:
    image: mongo-express
    ports: 
      - 3001:8081
    environment: 
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=my_mongo
    restart: unless-stopped
